### PR TITLE
Overhaul README.md

### PR DESCRIPTION
**Pull request by omasanori**
This is a work-in-progress. Any suggestions would be highly appreciated.

Build prerequisites are now described as the canonical source, so no one is ready to kick the tires before reading the full instructions. Thus, this README.md is essentially the getting started guide of BlackParrot at this moment.

This PR aims for a significant revision of README.md to improve readability and make BlackParrot easier to get involved.

### CODE REVIEW

**Comment by taylor-bsg** [comment]
Dan will review but thank you for jumping in, @omasanori !

**Comment by dpetrisko** [comment]
Looks great. The "tire kick" example is meant to be run without needing to install most of the dependencies, which is why it is chronologically before. I believe the dependencies needed for that are simply those needed for Verilator. Perhaps it makes sense to have separate dependencies for prep_lite and prep? As a followup, it would be useful to list what is included as part of prep_lite and prep

**Comment by omasanori** [comment]
Thank you, @dpetrisko , @taylor-bsg !

> I believe the dependencies needed for that are simply those needed for Verilator. 

riscv-gnu-toolchain requires some more, but indeed OpenJDK for instance is unnecessary for tire_kick.

> Perhaps it makes sense to have separate dependencies for prep_lite and prep? As a followup, it would be useful to list what is included as part of prep_lite and prep

Sounds great, I will try.

**Comment by dpetrisko** [comment]
>riscv-gnu-toolchain requires some more, but indeed OpenJDK for instance is unnecessary for tire_kick.

I believe tire_kick actually only needs Verilator, not riscv-gnu-toolchain:
https://github.com/black-parrot/black-parrot/blob/master/bp_top/test/tb/bp_tethered/Makefile.verilator#L110

Perhaps the right getting started structure then is:
- make verilator, tire_kick
- make prep_lite, compile and run a verilator test
- make prep, compile and parse with surelog
- make prep_bsg, compile and run VCS test

what do you think?

**Comment by omasanori** [comment]
Ah, now I got it. The proposed flow sounds good to me. I will ping if the rearrangement is done.

**Comment by dpetrisko** [comment]
Merging this as part of docker overhaul. Thanks!

**Pull request merged**
